### ISSUE TITLE
Repo is gone....

### ISSUE THREAD

**Issue by brutaldev** [Lebogang95/SeamlessPayRepo#1]
Just the other day I looked at this and now the repo (https://github.com/seamlesspayio/seamlesspay)  has been removed/privatized. Any reason for this?

**Comment by Lebogang95** [comment]
There are two reasons for this. I'm going to release version two of the repo which is much simpler to set up and easier to use and the second reason for removing the old repo is so that I can put version 2 under my own profile. It should be up by the end of January again, please check again then. Sorry for the inconvenience.

**Comment by brutaldev** [comment]
Awesome, looking forward to it!
